### ISSUE TITLE
Wind docstrins update

### ISSUE THREAD

**Issue by EdgarUbaldo** [FZJ-IEK3-VSA/RESKit#19]
- [ ] Core

1. - [ ] 	apply_air_density_adjustment
2. - [ ] 	onshore_turbine_from_avg_wind_speed
3. - [ ] 	apply_logarithmic_profile_projection
4. - [ ] 	synthetic_power_curve_data
5. - [ ] 	compute_specific_power
6. - [ ] 	PowerCurve
7. - [ ] 	from_specific_power
8. - [ ] 	from_capacity_and_rotor_diam
9. - [ ] 	simulate
10. - [ ] 	expectated_capacity_factor_from_weibull
11. - [ ] 	expectated_capacity_factor_from_distribution
12. - [ ] 	convolute_by_guassian
13. - [ ] 	apply_loss_factor
14. - [ ] 	apply_power_profile_projection
15. - [ ] 	alpha_from_levels
16. - [ ] 	parse_turbine
17. - [ ] 	TurbineLibrary
18. - [ ]  expectatedCapacityFactorFromWeibull
19. - [ ] 	expectatedCapacityFactorFromDistribution
20. - [ ] 	simulateTurbine
21. - [ ] 	fixVal

- [ ] Economic
1. - [x] 	offshore_turbine_capex
2. - [x] 	offshore_bos
3. - [x] 	onshore_turbine_capex
4. - [x] 	onshore_tcc
5. - [x] 	onshore_bos

- [ ] Workflow

1. - [ ] 	WindWorkflowManager
2. - [ ] 	set_roughness
3. - [ ] 	estimate_roughness_from_land_cover
4. - [ ] 	logarithmic_projection_of_wind_speeds_to_hub_height
5. - [ ] 	apply_air_density_correction_to_wind_speeds
6. - [ ] 	convolute_power_curves
7. - [ ] 	simulate
8. - [ ] 	onshore_wind_merra_ryberg2019_europe
9. - [ ] 	offshore_wind_merra_caglayan2019
10. - [ ] 	offshore_wind_era5_unvalidated
11. - [ ] 	onshore_wind_era5_unvalidated

- [ ] Revise it and send it to Felina for feed-back

- [ ] Incorporate Felina's feedback and send merge request

**Comment by dsryberg** [comment]
@EdgarUbaldo It looks like you are working on the "master" branch, which is not quite right. Be sure you have the "restruct" branch checked out. Otherwise, you may end writing doc strings for functions which have changed are deleted

**Comment by EdgarUbaldo** [comment]
Thank you, Sev. In deed, I was working on the master branch. I changed to the restructuring one and updated the to-do list.
