### ISSUE TITLE
Decide on DocString style

### ISSUE THREAD

**Issue by sevberg** [FZJ-IEK3-VSA/RESKit#8]

**Comment by EdgarUbaldo** [comment]
This post explains the purpose of docstrings and gives a short comparison of the different styles we could use https://www.datacamp.com/community/tutorials/docstrings-python

Initially, we will start working with the Numpy Style for it being easy to read and Sphinx compatible. We could change later on but this is a start.

**Comment by dsryberg** [comment]
More info on Numpy/SciPy style [HERE](https://numpydoc.readthedocs.io/en/latest/format.html)

**Comment by Zaubeerer** [comment]
Hey, why not this style combining type hints with docstrings (e.g. numpy style?)?

https://github.com/agronholm/sphinx-autodoc-typehints

**Comment by dsryberg** [comment]
Doesn't this require using Sphinx style? During our meeting today we thought that Numpy style is the simplest and therefore would be good for a first iteration. But if it's possible to mix these type hints together with Numpy, then yeah! why not!?

Or would you suggest we go with Sphinx from the beginning?

**Comment by r-beer** [comment]
We can have both :) 

https://pypi.org/project/sphinx-autodoc-napoleon-typehints/

Just found this, what do you think about it?

Sphinx with numpy style and typehints 👌
